// Builds the tokens/ outputs from tokens/source/figma-styles.json (a raw export of the Figma styles).
// Usage: node tooling/build-tokens.js
// Writes: tokens/colors.json, tokens/typography.json, tokens/tokens.css, tokens/elementor-globals.md
// Re-export figma-styles.json from Figma whenever styles change (see docs/maintaining.md), then re-run this.
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const src = JSON.parse(fs.readFileSync(path.join(root, 'tokens/source/figma-styles.json'), 'utf8'));

const slug = s => s.toLowerCase().replace(/®|™/g, '').replace(/·/g, '').replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const rgba = (hex, a) => {
  const n = parseInt(hex.slice(1), 16);
  const [r, g, b] = [n >> 16, (n >> 8) & 255, n & 255];
  return a >= 1 ? hex : `rgba(${r}, ${g}, ${b}, ${+a.toFixed(2)})`;
};

// ---- colours
const colors = src.paints.map(p => {
  const t = { name: p.name, cssVar: `--cp-${slug(p.name)}`, description: p.description };
  if (p.type === 'solid') { t.type = 'color'; t.hex = p.hex; t.opacity = p.opacity; t.css = rgba(p.hex, p.opacity); }
  else { t.type = 'gradient'; t.css = `linear-gradient(${p.direction}, ${p.stops.map(s => `${rgba(s.hex, s.alpha)} ${Math.round(s.position * 100)}%`).join(', ')})`; t.stops = p.stops; }
  t.flagged = p.name.startsWith('Flagged/');
  return t;
});

// ---- type
const type = src.text.map(line => {
  const [name, family, weight, size, lineHeight, letterSpacing, upper, added] = line.split('|');
  const px = +size;
  const lh = lineHeight === 'auto' ? 'normal' : lineHeight.endsWith('%') ? (parseFloat(lineHeight) / 100).toString() : lineHeight;
  const ls = letterSpacing.endsWith('%') ? `${(parseFloat(letterSpacing) / 100).toFixed(3).replace(/\.?0+$/, '') || 0}em` : letterSpacing;
  const [group] = name.split('/');
  return { name, group, cssClass: `.cp-${slug(name)}`, family, weight: +weight, size: px, lineHeight: lh, letterSpacing: ls, textTransform: upper === 'U' ? 'uppercase' : 'none', keyword: /Keyword/.test(name), addedDuringBuild: added === 'A' };
});

fs.writeFileSync(path.join(root, 'tokens/colors.json'), JSON.stringify(colors, null, 2) + '\n');
fs.writeFileSync(path.join(root, 'tokens/typography.json'), JSON.stringify(type, null, 2) + '\n');

// ---- CSS
let css = `/* Clark Pacific web design system — generated by tooling/build-tokens.js from the Figma styles. Do not edit by hand. */\n`;
css += `@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@200;300;400;600&display=swap');\n\n:root {\n`;
for (const c of colors) css += `  ${c.cssVar}: ${c.css};${c.flagged ? ' /* FLAGGED: confirm before use */' : ''}\n`;
css += `}\n\n/* Type styles. Desktop classes apply at 1440; use the Mobile classes (or the media query below) at 390. */\n`;
for (const t of type) {
  if (t.group === 'Mobile') continue;
  css += `${t.cssClass} { font-family: '${t.family}', sans-serif; font-weight: ${t.weight}; font-size: ${t.size}px; line-height: ${t.lineHeight}; letter-spacing: ${t.letterSpacing}; text-transform: ${t.textTransform}; }\n`;
}
css += `\n@media (max-width: 767px) {\n`;
for (const t of type.filter(x => x.group === 'Mobile')) {
  const desk = `.cp-${slug(t.name.replace('Mobile/', 'Desktop/'))}`;
  const sel = type.find(x => x.name === t.name.replace('Mobile/', 'Desktop/')) ? `${desk}, ${t.cssClass}` : t.cssClass;
  css += `  ${sel} { font-family: '${t.family}', sans-serif; font-weight: ${t.weight}; font-size: ${t.size}px; line-height: ${t.lineHeight}; letter-spacing: ${t.letterSpacing}; text-transform: ${t.textTransform}; }\n`;
}
css += `}\n`;
for (const t of type.filter(x => x.group === 'Mobile')) {
  css += `${t.cssClass} { font-family: '${t.family}', sans-serif; font-weight: ${t.weight}; font-size: ${t.size}px; line-height: ${t.lineHeight}; letter-spacing: ${t.letterSpacing}; text-transform: ${t.textTransform}; }\n`;
}
fs.writeFileSync(path.join(root, 'tokens/tokens.css'), css);

// ---- Elementor mapping
let md = `# Elementor Global Colors and Global Fonts\n\nGenerated by \`tooling/build-tokens.js\`. The names match the Figma styles one-to-one, so the build and the design file share one vocabulary.\n\n`;
md += `## Global Colors\n\n| Global Color (= Figma style) | Value | Use |\n|---|---|---|\n`;
for (const c of colors.filter(c => c.type === 'color')) md += `| ${c.name}${c.flagged ? ' ⚑' : ''} | \`${c.css}\` | ${(c.description || '').replace(/\|/g, '/')} |\n`;
md += `\n⚑ Flagged colours were found in the approved source but are not on the token list. Confirm or remap them before creating them as globals.\n\n`;
md += `## Gradients (not Elementor globals — apply as background overlays)\n\n| Style | CSS |\n|---|---|\n`;
for (const c of colors.filter(c => c.type === 'gradient')) md += `| ${c.name} | \`${c.css}\` |\n`;
md += `\n## Global Fonts\n\nOne Global Font per role, with the Desktop value as the base and the Mobile value as the responsive override.\n\n| Global Font | Weight | Desktop size / line height | Mobile size / line height | Letter spacing | Case |\n|---|---|---|---|---|---|\n`;
const roles = [...new Set(type.filter(t => t.group !== 'Utility').map(t => t.name.split('/')[1]))];
for (const r of roles) {
  const d = type.find(t => t.name === 'Desktop/' + r), m = type.find(t => t.name === 'Mobile/' + r);
  const a = d || m;
  md += `| ${r}${a.addedDuringBuild ? ' †' : ''} | ${a.weight} | ${d ? `${d.size}px / ${d.lineHeight}` : '—'} | ${m ? `${m.size}px / ${m.lineHeight}` : '—'} | ${a.letterSpacing} | ${a.textTransform === 'uppercase' ? 'Upper' : 'As typed'} |\n`;
}
md += `\n† Added during the Figma build for roles found in the source outside the documented scale — confirm or fold into an existing tier.\n\n`;
md += `**Two-weight headlines:** apply the base role (e.g. Heading, Light) to the whole headline and the matching "Keyword" role (SemiBold, same size) to the last one to three words. Never use Bold (700).\n\n`;
md += `**Utility:** ${type.filter(t => t.group === 'Utility').map(t => `${t.name.split('/')[1]} (${t.family} ${t.weight}, ${t.size}px)`).join('; ')}. Placeholder Caption is for image placeholders only.\n`;
fs.writeFileSync(path.join(root, 'tokens/elementor-globals.md'), md);

console.log(`colors: ${colors.length}  type styles: ${type.length}  → tokens/`);
